export PATH=$ANDROID_HOME/platform-tools:$PATH
export PATH=$ANDROID_HOME/tools:$PATH

alias adb='/Users/Development/Library/Android/sdk/platform-tools/adb'
alias dynamodb='nohup java -Djava.library.path=./DynamoDBLocal_lib -jar /Users/Development/dynamodb/dynamodb_local_latest/DynamoDBLocal.jar -sharedDb &'
alias redis-server='redis-server --daemonize yes'
alias marriadb='mysql.server start'
alias emulatorStart='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed full'

alias emulator1='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed gsm'
alias emulator2='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed hscsd'
alias emulator3='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed gprs'
alias emulator4='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed edge'
alias emulator5='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed umts'
alias emulator6='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed hsdpa'

alias emulator7='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay gprs -netspeed full'
alias emulator8='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay edge -netspeed full'
alias emulator9='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay umts -netspeed full'
alias emulator10='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netdelay none -netspeed full'

alias emulator11='$ANDROID_HOME/tools/emulator -avd Pixel_C_API_23 -netspeed 2.9,3.1 -netdelay none'
alias emulatorNexus='$ANDROID_HOME/tools/emulator -avd Nexus_6_API_27 -netspeed full -netdelay none'

alias rnra='react-native run-android'
alias adbl='adb logcat'
alias gita='git add —-all'
alias gitc='git commit -m'
alias gitpl='git pull'
alias gitph='git push'
alias gitsh='git stash'
alias gitss='git status'
alias gitco='git checkout'
alias gitl='git log'
alias gitb='git branch'
alias gitba='git branch --all'
alias gitd='git diff'
alias adbue='adb uninstall com.electricmirrorapp'
alias adbur='adbue & rnra'
alias adbupr='adbue & adb install /Users/Development/em/hospitality-ui/android/app/release/app-release.apk'
alias adbtk='adb shell input text "1_7UrgbtUSRN"'
alias mfbdb='mysql -u emsmp -pVKgr7MdaZ]ZjkyiVDfPHsA*Bvy6 -h em.cajwk6zlvqwp.us-west-2.rds.amazonaws.com em'
alias adbdr='adb logcat '*:S' ReactNative:V ReactNativeJS:V'
alias adbd='adb devices'
alias rr='adb shell input keyevent 82'
alias adbcm='adb shell du -h /storage/emulated/0/snowboy/'

alias cdhu='cd /Users/Development/em/hospitality-ui'
alias cdha='cd /Users/Development/em/hospitality-admin'
alias cdca='cd /Users/Development/em/console-api'
alias cdda='cd /Users/Development/em/device-api'
alias cdho='cd /Users/Development'
alias cdem='cd /Users/Development/em'
alias startServers='redis-server & marriadb & dynamodb'
alias startApis='cdca & gulp & cdda & gulp'
alias adbb='react-native bundle --platform=android --dev=false --entry-file=index.android.js \
  --bundle-output=android/app/src/main/assets/index.android.bundle \
  --assets-dest=android/app/src/main/res/'
alias adbra='adb shell am start -n com.electricmirrorapp/.MainActivity'
alias adbtr='adb shell input text "JDB"'
alias adbtq1='adb shell input text "what time is it"'
alias adbtq2='adb shell input text "what are the pool hours"'
alias adbtq3='adb shell input text "play classical music"'
alias vbash='vim /Users/Development/.bash_profile'

